- name: creation of ec2 instance and adding to load balancer and auto scaling group
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes

  vars:
    region: us-east-1
    instance_type: t2.micro
    ami: ami-0b898040803850657
    keypair: *******

  tasks:

   - name: EC2 instance creation
     ec2:
      instance_type: "{{instance_type}}"
      key_name: "{{keypair}}"
      image: "{{ami}}"
      region: "{{region}}"
      aws_access_key: ***************
      aws_secret_key: ********************
      group: default
      count: 1
      vpc_subnet_id: subnet-867753a8
      wait: yes
      assign_public_ip: yes

   - name: Get my current IP address
     uri:
     url: http://checkip.amazonaws.com/
     return_content: yes
     register: my_ip

   - name: EC2 security group creation
     ec2_group:
       name: pink
       description: the security group for pink
       vpc_id: vpc-55b3d92f
       aws_access_key: ***************
       aws_secret_key: ********************
       region: "{{region}}"
       rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: "{{ my_ip.content | replace('\n', '') }}/32"
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ my_ip.content | replace('\n', '') }}/32"
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: "{{ my_ip.content | replace('\n', '') }}/32"
          rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
   
   - name: Apache Installation
     yum:
       name: httpd
       state: present
   - name: ensure httpd is running 
     service:
       name: httpd
       state: started
   - name: Open port 80 for http access
     firewalld:
       service: http
       permanent: true
       state: enabled
   - name: setup firewalld
     firewalld:
       service: http
       permanent: true
       state: enabled
   - name: Restart the firewalld service to load in the firewall changes
     service:
       name: firewalld
       state: restarted

   - name: elb creation
     ec2_elb_lb:
       name: abi-load-balancer
       state: present
       region: "{{region}}"   
       aws_access_key: ***************
       aws_secret_key: ********************
      zones:
       - us-east-1a
       - us-east-1b
      listeners:
       - protocol: http
         load_balancer_port: 80
         instance_port: 80
      health_check:
         ping_protocol: http
         ping_port: 80
         ping_path: "/index.html"
         response_timeout: 10
         interval: 20
         unhealthy_threshold: 2
         healthy_threshold: 10

   - name: add the instance
     ec2_elb:
         instance_id: i-074a33941237ef159
         ec2_elbs: abi-load-balancer
         aws_access_key: ***************
         aws_secret_key: ********************
         state: present
         region: "{{region}}"

   - name: create ec2 launch config
     ec2_lc:
         name: abi_launch
         image_id: ami-0b898040803850657
         aws_access_key: ***************
         aws_secret_key: ********************
         instance_type: "{{instance_type}}"
         key_name: *******
         security_groups: 'pink'
         region: "{{region}}"
         assign_public_ip: yes

   - name: creation of auto scaling group
     ec2_asg:
        name: abiautogroup
        region: "{{region}}"
        aws_access_key: ***************
        aws_secret_key: ********************
        load_balancers: abi-load-balancer
        availability_zones: ['us-east-1a']
        launch_config_name: 'abi_launch'
        min_size: 1
        max_size: 1
        desired_capacity: 1
        replace_all_instances: yes
        vpc_zone_identifier: ['subnet-867753a8']
